@startuml
top to bottom direction
skinparam classAttributeIconSize 0
skinparam linetype ortho
hide empty members

abstract class VideoClass {
  - id: String
  - duration: int
  - videoLocation: String
  + VideoClass(String, int, String)
  + VideoClass(String)
  + getId(): String
  + getDuration(): int
  + getVideoLocation(): String
  + equals(Object): boolean
  + hashCode(): int
}

interface Video {
  + getId(): String
  + getDuration(): int
  + getVideoLocation(): String
}

interface PublishableVideo {
  + getTitle(): String
  + getPublisher(): String
  + getLanguage(): Locale
}

interface PremiumVideo {
  + addSubtitle(Subtitle): void
  + getSubtitles(): Iterator<Subtitle>
}

interface Episode {
  + getDate(): String
}

class PublishableVideoClass {
  - title: String
  - publisher: String
  - language: Locale
  + PublishableVideoClass(String, int, String, String, String, Locale)
  + PublishableVideoClass(String)
  + getTitle(): String
  + getPublisher(): String
  + getLanguage(): Locale
}

class PremiumVideoClass {
  - subtitles: Array<Subtitle>
  + PremiumVideoClass(String, int, String, String, String, Locale, Subtitle)
  - addInitialSubtitle(Subtitle): void
  + addSubtitle(Subtitle): void
  + getSubtitles(): Iterator<Subtitle>
}

class EpisodeClass {
  - date: String
  + EpisodeClass(String, int, String, String)
  + EpisodeClass(String)
  + getDate(): String
}

interface Podcast {
  + getTitle(): String
  + getAuthor(): String
  + getLanguage(): Locale
  + isUnique(String): boolean
  + isNewer(String): boolean
  + addEpisode(Episode): void
  + getLastestDate(): String
  + hasEpisodes(): boolean
  + getEpisodes(): Iterator<Episode>
}

class PodcastClass {
  - episodes: Array<Episode>
  - title: String
  - author: String
  - language: Locale
  + PodcastClass(String, String, Locale)
  + PodcastClass(String)
  + getTitle(): String
  + getAuthor(): String
  + getLanguage(): Locale
  + isUnique(String): boolean
  + isNewer(String): boolean
  + addEpisode(Episode): void
  + getLastestDate(): String
  + hasEpisodes(): boolean
  + getEpisodes(): Iterator<Episode>
  - hasNoEpisodes(): boolean
  + equals(Object): boolean
  + hashCode(): int
}

interface Show {
  + getTitle(): String
  + getDate(): String
  + getAuthor(): String
}

class ShowClass {
  - title: String
  - author: String
  - transmissionDate: String
  + ShowClass(String)
  + ShowClass(String, String, String)
  + getTitle(): String
  + getDate(): String
  + getAuthor(): String
  + equals(Object): boolean
  + hashCode(): int
}

class Subtitle <<record>> {
  - language: Locale
  - location: String
  + Subtitle(Locale, String)
  + getLanguage(): Locale
  + getLocation(): String
}

interface YouVideoApp {
  + addPublishable(String, int, String, String, String, Locale): void
  + addPremium(String, int, String, String, String, Locale, String, Locale): void
  + addSubtitle(String, Locale, String): void
  + addPodcast(String, String, Locale): void
  + addEpisode(String, String, int, String, String): void
  + createShow(String, String, String): void
  + removePodcast(String): void
  + removeShow(String): void
  + removeVideo(String): void
  + getVideo(String): PublishableVideo
  + getPodcast(String): Podcast
  + getShow(String): Show
  + getPodcastsByAuthor(String): Iterator<Podcast>
  + isUniqueVideo(String): boolean
  + isUniquePodcast(String): boolean
  + isUniqueEpisode(String): boolean
  + isUniqueShow(String): boolean
  + isNewer(String, String): boolean
  + isPremium(String): boolean
  + isEpisode(String): boolean
  + isVideoUsedInShow(String): boolean
  + hasEpisodesPodcast(String): boolean
  + getStoredAuthorName(String): String
}

class YouVideoAppClass {
  - videos: Array<PublishableVideo>
  - podcasts: Array<Podcast>
  - shows: Array<Show>
  + YouVideoAppClass()
  + addPublishable(String, int, String, String, String, Locale): void
  + addPremium(String, int, String, String, String, Locale, String, Locale): void
  + addSubtitle(String, Locale, String): void
  + addPodcast(String, String, Locale): void
  + addEpisode(String, String, int, String, String): void
  + createShow(String, String, String): void
  + removePodcast(String): void
  + removeShow(String): void
  + removeVideo(String): void
  + getVideo(String): PublishableVideo
  + getPodcast(String): Podcast
  + getShow(String): Show
  + getPodcastsByAuthor(String): Iterator<Podcast>
  + isUniqueVideo(String): boolean
  + isUniquePodcast(String): boolean
  + isUniqueEpisode(String): boolean
  + isUniqueShow(String): boolean
  + isNewer(String, String): boolean
  + isPremium(String): boolean
  + isEpisode(String): boolean
  + isVideoUsedInShow(String): boolean
  + hasEpisodesPodcast(String): boolean
  + getStoredAuthorName(String): String
  {static} + isValidLanguage(String): boolean
  - findVideo(String): PublishableVideo
  - findPodcast(String): Podcast
  - findShow(String): Show
}

Video <|-- PublishableVideo
Video <|-- Episode
PublishableVideo <|-- PremiumVideo

VideoClass ..|> Video
PublishableVideoClass --|> VideoClass
PublishableVideoClass ..|> PublishableVideo
PremiumVideoClass --|> PublishableVideoClass
PremiumVideoClass ..|> PremiumVideo
EpisodeClass --|> VideoClass
EpisodeClass ..|> Episode

PodcastClass ..|> Podcast
ShowClass ..|> Show
YouVideoAppClass ..|> YouVideoApp

PremiumVideoClass *-- "0..*" Subtitle : subtitles
PodcastClass *-- "0..*" Episode : episodes

YouVideoAppClass *-- "0..*" PublishableVideo : videos
YouVideoAppClass *-- "0..*" Podcast : podcasts
YouVideoAppClass *-- "0..*" Show : shows

YouVideoAppClass ..> PublishableVideoClass : create
YouVideoAppClass ..> PremiumVideoClass : create
YouVideoAppClass ..> PodcastClass : create
YouVideoAppClass ..> EpisodeClass : create
YouVideoAppClass ..> ShowClass : create
YouVideoAppClass ..> Subtitle : create

@enduml